/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountType = { 'checking' : null } |
  { 'savings' : null };
export interface BankAccount {
  'balance' : bigint,
  'owner' : Principal,
  'accountType' : AccountType,
  'accountNumber' : bigint,
  'accountLabel' : string,
}
export interface DashboardData {
  'recentTransactions' : Array<Transaction>,
  'accounts' : Array<BankAccount>,
}
export type PasswordHash = string;
export interface PublicUserProfile {
  'fullName' : string,
  'email' : string,
  'phone' : string,
}
export type Time = bigint;
export interface Transaction {
  'transactionType' : TransactionType,
  'description' : string,
  'timestamp' : Time,
  'accountNumber' : bigint,
  'balanceAfter' : bigint,
  'amount' : bigint,
}
export type TransactionType = { 'credit' : null } |
  { 'debit' : null };
export interface TransferRequest {
  'fromAccount' : bigint,
  'description' : string,
  'passwordHash' : PasswordHash,
  'toAccount' : bigint,
  'amount' : bigint,
}
export type TransferResult = { 'insufficientFunds' : null } |
  { 'success' : [bigint, bigint] } |
  { 'accountNotFound' : null } |
  { 'unauthorized' : null } |
  { 'invalidAmount' : null };
export interface UserProfile {
  'fullName' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBankAccount' : ActorMethod<[AccountType, string, bigint], BankAccount>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardData' : ActorMethod<[], DashboardData>,
  'getPublicUserProfile' : ActorMethod<[Principal], [] | [PublicUserProfile]>,
  'getSecureUserProfile' : ActorMethod<[PasswordHash], [] | [UserProfile]>,
  'getTransactionHistory' : ActorMethod<[bigint], Array<Transaction>>,
  'getUserAccounts' : ActorMethod<[Principal], Array<BankAccount>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveSecureUserProfile' : ActorMethod<[UserProfile, PasswordHash], undefined>,
  'transferFunds' : ActorMethod<[TransferRequest], TransferResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];