/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AccountType = IDL.Variant({
  'checking' : IDL.Null,
  'savings' : IDL.Null,
});
export const BankAccount = IDL.Record({
  'balance' : IDL.Int,
  'owner' : IDL.Principal,
  'accountType' : AccountType,
  'accountNumber' : IDL.Nat,
  'accountLabel' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const TransactionType = IDL.Variant({
  'credit' : IDL.Null,
  'debit' : IDL.Null,
});
export const Time = IDL.Int;
export const Transaction = IDL.Record({
  'transactionType' : TransactionType,
  'description' : IDL.Text,
  'timestamp' : Time,
  'accountNumber' : IDL.Nat,
  'balanceAfter' : IDL.Int,
  'amount' : IDL.Int,
});
export const DashboardData = IDL.Record({
  'recentTransactions' : IDL.Vec(Transaction),
  'accounts' : IDL.Vec(BankAccount),
});
export const PublicUserProfile = IDL.Record({
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const PasswordHash = IDL.Text;
export const TransferRequest = IDL.Record({
  'fromAccount' : IDL.Nat,
  'description' : IDL.Text,
  'passwordHash' : PasswordHash,
  'toAccount' : IDL.Nat,
  'amount' : IDL.Int,
});
export const TransferResult = IDL.Variant({
  'insufficientFunds' : IDL.Null,
  'success' : IDL.Tuple(IDL.Int, IDL.Int),
  'accountNotFound' : IDL.Null,
  'unauthorized' : IDL.Null,
  'invalidAmount' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBankAccount' : IDL.Func(
      [AccountType, IDL.Text, IDL.Int],
      [BankAccount],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardData' : IDL.Func([], [DashboardData], ['query']),
  'getPublicUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PublicUserProfile)],
      ['query'],
    ),
  'getSecureUserProfile' : IDL.Func([PasswordHash], [IDL.Opt(UserProfile)], []),
  'getTransactionHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserAccounts' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(BankAccount)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveSecureUserProfile' : IDL.Func([UserProfile, PasswordHash], [], []),
  'transferFunds' : IDL.Func([TransferRequest], [TransferResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AccountType = IDL.Variant({
    'checking' : IDL.Null,
    'savings' : IDL.Null,
  });
  const BankAccount = IDL.Record({
    'balance' : IDL.Int,
    'owner' : IDL.Principal,
    'accountType' : AccountType,
    'accountNumber' : IDL.Nat,
    'accountLabel' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const TransactionType = IDL.Variant({
    'credit' : IDL.Null,
    'debit' : IDL.Null,
  });
  const Time = IDL.Int;
  const Transaction = IDL.Record({
    'transactionType' : TransactionType,
    'description' : IDL.Text,
    'timestamp' : Time,
    'accountNumber' : IDL.Nat,
    'balanceAfter' : IDL.Int,
    'amount' : IDL.Int,
  });
  const DashboardData = IDL.Record({
    'recentTransactions' : IDL.Vec(Transaction),
    'accounts' : IDL.Vec(BankAccount),
  });
  const PublicUserProfile = IDL.Record({
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const PasswordHash = IDL.Text;
  const TransferRequest = IDL.Record({
    'fromAccount' : IDL.Nat,
    'description' : IDL.Text,
    'passwordHash' : PasswordHash,
    'toAccount' : IDL.Nat,
    'amount' : IDL.Int,
  });
  const TransferResult = IDL.Variant({
    'insufficientFunds' : IDL.Null,
    'success' : IDL.Tuple(IDL.Int, IDL.Int),
    'accountNotFound' : IDL.Null,
    'unauthorized' : IDL.Null,
    'invalidAmount' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBankAccount' : IDL.Func(
        [AccountType, IDL.Text, IDL.Int],
        [BankAccount],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardData' : IDL.Func([], [DashboardData], ['query']),
    'getPublicUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PublicUserProfile)],
        ['query'],
      ),
    'getSecureUserProfile' : IDL.Func(
        [PasswordHash],
        [IDL.Opt(UserProfile)],
        [],
      ),
    'getTransactionHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserAccounts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(BankAccount)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveSecureUserProfile' : IDL.Func([UserProfile, PasswordHash], [], []),
    'transferFunds' : IDL.Func([TransferRequest], [TransferResult], []),
  });
};

export const init = ({ IDL }) => { return []; };