/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type PasswordHash = string;
export interface BankAccount {
    balance: bigint;
    owner: Principal;
    accountType: AccountType;
    accountNumber: bigint;
    accountLabel: string;
}
export type Time = bigint;
export interface PublicUserProfile {
    fullName: string;
    email: string;
    phone: string;
}
export type TransferResult = {
    __kind__: "insufficientFunds";
    insufficientFunds: null;
} | {
    __kind__: "success";
    success: [bigint, bigint];
} | {
    __kind__: "accountNotFound";
    accountNotFound: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
} | {
    __kind__: "invalidAmount";
    invalidAmount: null;
};
export interface DashboardData {
    recentTransactions: Array<Transaction>;
    accounts: Array<BankAccount>;
}
export interface TransferRequest {
    fromAccount: bigint;
    description: string;
    passwordHash: PasswordHash;
    toAccount: bigint;
    amount: bigint;
}
export interface UserProfile {
    fullName: string;
    email: string;
    address: string;
    phone: string;
}
export interface Transaction {
    transactionType: TransactionType;
    description: string;
    timestamp: Time;
    accountNumber: bigint;
    balanceAfter: bigint;
    amount: bigint;
}
export enum AccountType {
    checking = "checking",
    savings = "savings"
}
export enum TransactionType {
    credit = "credit",
    debit = "debit"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBankAccount(accountType: AccountType, accountLabel: string, initialBalance: bigint): Promise<BankAccount>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardData(): Promise<DashboardData>;
    getPublicUserProfile(user: Principal): Promise<PublicUserProfile | null>;
    getSecureUserProfile(passwordHash: PasswordHash): Promise<UserProfile | null>;
    getTransactionHistory(accountNumber: bigint): Promise<Array<Transaction>>;
    getUserAccounts(user: Principal): Promise<Array<BankAccount>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveSecureUserProfile(profile: UserProfile, passwordHash: PasswordHash): Promise<void>;
    transferFunds(request: TransferRequest): Promise<TransferResult>;
}
import type { AccountType as _AccountType, BankAccount as _BankAccount, DashboardData as _DashboardData, PublicUserProfile as _PublicUserProfile, Time as _Time, Transaction as _Transaction, TransactionType as _TransactionType, TransferResult as _TransferResult, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBankAccount(arg0: AccountType, arg1: string, arg2: bigint): Promise<BankAccount> {
        if (this.processError) {
            try {
                const result = await this.actor.createBankAccount(to_candid_AccountType_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_BankAccount_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBankAccount(to_candid_AccountType_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_BankAccount_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardData(): Promise<DashboardData> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardData();
                return from_candid_DashboardData_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardData();
            return from_candid_DashboardData_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicUserProfile(arg0: Principal): Promise<PublicUserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSecureUserProfile(arg0: PasswordHash): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSecureUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSecureUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionHistory(arg0: bigint): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionHistory(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionHistory(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserAccounts(arg0: Principal): Promise<Array<BankAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAccounts(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAccounts(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveSecureUserProfile(arg0: UserProfile, arg1: PasswordHash): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSecureUserProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSecureUserProfile(arg0, arg1);
            return result;
        }
    }
    async transferFunds(arg0: TransferRequest): Promise<TransferResult> {
        if (this.processError) {
            try {
                const result = await this.actor.transferFunds(arg0);
                return from_candid_TransferResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferFunds(arg0);
            return from_candid_TransferResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AccountType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountType): AccountType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_BankAccount_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BankAccount): BankAccount {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_DashboardData_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardData): DashboardData {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_TransferResult_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransferResult): TransferResult {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PublicUserProfile]): PublicUserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    recentTransactions: Array<_Transaction>;
    accounts: Array<_BankAccount>;
}): {
    recentTransactions: Array<Transaction>;
    accounts: Array<BankAccount>;
} {
    return {
        recentTransactions: from_candid_vec_n14(_uploadFile, _downloadFile, value.recentTransactions),
        accounts: from_candid_vec_n19(_uploadFile, _downloadFile, value.accounts)
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transactionType: _TransactionType;
    description: string;
    timestamp: _Time;
    accountNumber: bigint;
    balanceAfter: bigint;
    amount: bigint;
}): {
    transactionType: TransactionType;
    description: string;
    timestamp: Time;
    accountNumber: bigint;
    balanceAfter: bigint;
    amount: bigint;
} {
    return {
        transactionType: from_candid_TransactionType_n17(_uploadFile, _downloadFile, value.transactionType),
        description: value.description,
        timestamp: value.timestamp,
        accountNumber: value.accountNumber,
        balanceAfter: value.balanceAfter,
        amount: value.amount
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    balance: bigint;
    owner: Principal;
    accountType: _AccountType;
    accountNumber: bigint;
    accountLabel: string;
}): {
    balance: bigint;
    owner: Principal;
    accountType: AccountType;
    accountNumber: bigint;
    accountLabel: string;
} {
    return {
        balance: value.balance,
        owner: value.owner,
        accountType: from_candid_AccountType_n7(_uploadFile, _downloadFile, value.accountType),
        accountNumber: value.accountNumber,
        accountLabel: value.accountLabel
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    credit: null;
} | {
    debit: null;
}): TransactionType {
    return "credit" in value ? TransactionType.credit : "debit" in value ? TransactionType.debit : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    insufficientFunds: null;
} | {
    success: [bigint, bigint];
} | {
    accountNotFound: null;
} | {
    unauthorized: null;
} | {
    invalidAmount: null;
}): {
    __kind__: "insufficientFunds";
    insufficientFunds: null;
} | {
    __kind__: "success";
    success: [bigint, bigint];
} | {
    __kind__: "accountNotFound";
    accountNotFound: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
} | {
    __kind__: "invalidAmount";
    invalidAmount: null;
} {
    return "insufficientFunds" in value ? {
        __kind__: "insufficientFunds",
        insufficientFunds: value.insufficientFunds
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : "accountNotFound" in value ? {
        __kind__: "accountNotFound",
        accountNotFound: value.accountNotFound
    } : "unauthorized" in value ? {
        __kind__: "unauthorized",
        unauthorized: value.unauthorized
    } : "invalidAmount" in value ? {
        __kind__: "invalidAmount",
        invalidAmount: value.invalidAmount
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    checking: null;
} | {
    savings: null;
}): AccountType {
    return "checking" in value ? AccountType.checking : "savings" in value ? AccountType.savings : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BankAccount>): Array<BankAccount> {
    return value.map((x)=>from_candid_BankAccount_n5(_uploadFile, _downloadFile, x));
}
function to_candid_AccountType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): _AccountType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): {
    checking: null;
} | {
    savings: null;
} {
    return value == AccountType.checking ? {
        checking: null
    } : value == AccountType.savings ? {
        savings: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
